---

roles:
  - name: clusterverse
    src: https://github.com/dseeley/clusterverse
    version: master

  - name: opensearch
    src: https://github.com/dseeley/opensearch_ansible
    version: master

collections:
  - name: dseeley.ansible_vault_pipe
    source: https://galaxy.ansible.com
