---

- name: Get master-eligible nodes
  set_fact:
    master_eligible_nodes: |
      {%- set res = [] -%}
      {%- set master_eligible_hostnames = (groups['master'] if groups['master'] is defined else groups['data']) | sort -%}
      {%- for master_eligible_hostname in master_eligible_hostnames -%}
        {%- set _ = res.append({'hostname': master_eligible_hostname, 'ip': hostvars[master_eligible_hostname]['ansible_host']}) -%}
      {%- endfor -%}
      {{res}}

- name: master_eligible_nodes
  debug: msg={{master_eligible_nodes}}
  run_once: yes
