---

# Need to do this when we manually add systemd service files to the filesystem
- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: yes
  throttle: 1

## Restart opensearch nodes.  If this is not the initial install (the opensearch binary was not present), do each in-turn, ensuring each node is *really* back up (i.e. port 9200 is open) before restarting the next.
## This custom action plugin is a compromise, but there is apparently no alternative; see https://github.com/ansible/ansible/issues/80374
- name: restart opensearch
  become: yes
  dseeley.tasks_serial.tasks_serial:
    tasks:
      - name: service
        args:
          name: opensearch
          state: restarted
          enabled: yes
      - name: wait_for
        args:
          host: localhost
          port: 9200
          timeout: 300
  throttle: "{{ '1' if osearch_link_stat is defined and osearch_link_stat.stat.exists else '0' }}"
