---
- name: certs | admin cert
  block:
    - name: certs | Generate RSA private key
      community.crypto.openssl_privatekey_pipe:
        format: "pkcs8"
#        size: 2048
      register: r__openssl_privatekey_pipe__admin
      no_log: true

    - name: certs | Generate CSR
      community.crypto.openssl_csr_pipe:
        privatekey_content: "{{r__openssl_privatekey_pipe__admin.privatekey}}"
        basic_constraints: ["CA:FALSE"]
        basic_constraints_critical: yes
        key_usage: ["digitalSignature", "keyEncipherment", "nonRepudiation"]
        key_usage_critical: yes
        extended_key_usage: ["clientAuth"]
        extended_key_usage_critical: yes
        subject: { DC: "{{cluster_vars.dns_user_domain}}", CN: "admin" }
        use_common_name_for_san: no
      register: r__openssl_csr_pipe__admin

    - name: certs | Generate the self-signed certificate
      community.crypto.x509_certificate_pipe:
        provider: ownca
        ownca_content: "{{ssl_ownca['ca-crt.pem']}}"
        ownca_privatekey_content: "{{ssl_ownca['ca-key.pem']}}"
        csr_content: "{{r__openssl_csr_pipe__admin.csr}}"
        selfsigned_not_after: "+3652d"       # Expiry in 10 years (incl leap years)
      register: r__x509_certificate_pipe__admin
  run_once: yes
  delegate_to: localhost

- name: certs | host certs
  block:
    - name: certs | Generate RSA private key
      community.crypto.openssl_privatekey_pipe:
        format: "pkcs8"
#        size: 2048
      register: r__openssl_privatekey_pipe
      no_log: true

    - name: certs | Generate CSR
      community.crypto.openssl_csr_pipe:
        privatekey_content: "{{r__openssl_privatekey_pipe.privatekey}}"
        basic_constraints: ["CA:FALSE"]
        basic_constraints_critical: yes
        key_usage: ["digitalSignature", "keyEncipherment", "nonRepudiation"]
        key_usage_critical: yes
        extended_key_usage: ["clientAuth", "serverAuth"]
        extended_key_usage_critical: yes
        subject: { DC: "{{cluster_vars.dns_user_domain}}", CN: "{{ansible_hostname}}.{{cluster_vars.dns_user_domain}}" }
        subject_alt_name: |-
          {% set SANs = [] %}
          {% set _ = SANs.extend(['DNS:' + ansible_hostname,'DNS:' + ansible_hostname + '.' + cluster_vars.dns_user_domain]) -%}
          {% if (cluster_vars.dns_server is not defined  or  cluster_vars.dns_server == "") %}
          {% set _ = SANs.append('IP:' + ansible_host) %}
          {%- endif %}
          {{ SANs }}
      register: r__openssl_csr_pipe

    - name: certs | Generate the self-signed certificate
      community.crypto.x509_certificate_pipe:
        provider: ownca
        ownca_content: "{{ssl_ownca['ca-crt.pem']}}"
        ownca_privatekey_content: "{{ssl_ownca['ca-key.pem']}}"
        csr_content: "{{r__openssl_csr_pipe.csr}}"
        selfsigned_not_after: "+3652d"       # Expiry in 10 years (incl leap years)
      register: r__x509_certificate_pipe

- name: certs | copy certs to remote
  block:
    - name: certs | create cert directory on remote
      file: path={{osearch_conf_dir}} state=directory owner={{osearch_user}} group={{osearch_group}}

    - name: certs | Copy SSL certificates to remote
      copy:
        content: "{{ item.val }}"
        dest: "{{ item.path }}"
        mode: "{{ item.mode }}"
        owner: "{{ osearch_user }}"
        group: "{{ osearch_group }}"
        force: no               # Only create these if they don't already exist
      no_log: true
      with_items:
        - { path: '{{osearch_ssl_certificate_authority}}', val: "{{ssl_ownca['ca-crt.pem']}}", mode: '0600' }
        - { path: '{{osearch_ssl_certificate}}', val: "{{r__x509_certificate_pipe.certificate}}", mode: '0600' }
        - { path: '{{osearch_ssl_key}}', val: "{{r__openssl_privatekey_pipe.privatekey}}", mode: '0600' }
        - { path: '{{osearch_admin_certificate}}', val: "{{r__x509_certificate_pipe__admin.certificate}}", mode: '0600' }
        - { path: '{{osearch_admin_key}}', val: "{{r__openssl_privatekey_pipe__admin.privatekey}}", mode: '0600' }
  become: yes
  notify: restart opensearch
