---

## Using searchguard offline TLS tool to create node & root certificates
- name: Security Plugin configuration | Create local temporary directory for certificates generation
  local_action:
    module: file
    path: /tmp/opensearch-nodecerts
    state: directory
  run_once: true
  notify: restart opensearch

- name: Security Plugin configuration | Download certificates generation tool
  local_action:
    module: get_url
    url: https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-tlstool/1.5/search-guard-tlstool-1.5.tar.gz
    dest: /tmp/opensearch-nodecerts/search-guard-tlstool.tar.gz
  run_once: true
  notify: restart opensearch

- name: Security Plugin configuration | Extract the certificates generation tool
  local_action: command chdir=/tmp/opensearch-nodecerts tar -xvf search-guard-tlstool.tar.gz
  run_once: true
  notify: restart opensearch

- name: Security Plugin configuration | Make the executable file
  local_action:
    module: file
    dest: /tmp/opensearch-nodecerts/tools/sgtlstool.sh
    mode: a+x
  run_once: true
  notify: restart opensearch

- name: Security Plugin configuration | Prepare the certificates generation template file
  local_action:
    module: template
    src: tlsconfig.yml
    dest: /tmp/opensearch-nodecerts/config/tlsconfig.yml
  run_once: true
  notify: restart opensearch

- name: Security Plugin configuration | Generate the node & admin certificates in local
  local_action:
    module: command /tmp/opensearch-nodecerts/tools/sgtlstool.sh -c /tmp/opensearch-nodecerts/config/tlsconfig.yml -ca -crt -t /tmp/opensearch-nodecerts/config/
  run_once: true
  notify: restart opensearch

- name: Security Plugin configuration | Copy the node & admin certificates to opensearch nodes
  become: yes
  copy:
    src: "/tmp/opensearch-nodecerts/config/{{ item }}"
    dest: "{{ osearch_conf_dir }}"
    mode: 0600
    owner: "{{ osearch_user }}"
    group: "{{ osearch_group }}"
    force: yes
  with_items:
    - root-ca.pem
    - root-ca.key
    - "{{ inventory_hostname }}.key"
    - "{{ inventory_hostname }}.pem"
    - admin.key
    - admin.pem
  notify: restart opensearch

- name: Security Plugin configuration | Set the folder permission
  become: yes
  file:
    dest: "{{ osearch_conf_dir }}"
    owner: "{{ osearch_user }}"
    group: "{{ osearch_group }}"
    mode: 0700

- name: Security Plugin configuration | Cleanup local temporary directory
  local_action:
    module: file
    path: /tmp/opensearch-nodecerts
    state: absent
  run_once: true
