---

- name: opensearch/install-config | Create pid, log and conf directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{osearch_user}}"
    group: "{{osearch_group}}"
    mode: "2755"
  with_items:
    - "{{osearch_pid_dir}}"
    - "{{osearch_log_dir}}"
    - "{{osearch_conf_dir}}"

#Create data directory if mountpoint doesn't exist already
- name: opensearch/install-config | Create data dir if it doesn't exist
  become: yes
  file:
    path: "{{osearch_data_dir}}"
    state: directory
    owner: "{{osearch_user}}"
    group: "{{osearch_group}}"
    mode: 0755
  notify: restart opensearch

- name: opensearch/install-config | Create systemd file
  become: yes
  template:
    src: etc/systemd/system/opensearch.service.j2
    dest: /etc/systemd/system/opensearch.service
    mode: 0644
    force: yes
  notify:
  - reload systemd configuration
  - restart opensearch

- name: opensearch/install-config | Create jvm.options file
  become: yes
  template:
    src: opt/opensearch/config/jvm.options.j2
    dest: "{{osearch_conf_dir}}/jvm.options"
    owner: "{{osearch_user}}"
    group: "{{osearch_group}}"
    mode: 0600
    force: yes
  notify: restart opensearch
  vars:
    osearch_heap_size: "{{ (ansible_memtotal_mb / 2) | round | int | abs }}m"

- name: opensearch/install-config | Create main opensearch config file
  become: yes
  template:
    src: opt/opensearch/config/opensearch.yml.j2
    dest: "{{osearch_conf_dir}}/opensearch.yml"
    owner: "{{osearch_user}}"
    group: "{{osearch_group}}"
    mode: '0600'
    force: yes
  notify: restart opensearch

- name: opensearch/install-config | Create tmpfiles.d
  become: yes
  copy:
    content: |
      d    {{ osearch_pid_dir }}   0755 {{ osearch_user }} {{ osearch_group }} - -
    dest: "/usr/lib/tmpfiles.d/opensearch.conf"
    owner: "{{osearch_user}}"
    group: "{{osearch_group}}"
    mode: 0644
    force: yes
  notify: restart opensearch

- name: opensearch/install-config | Create unicast_hosts.txt (don't notify restart)
  become: yes
  copy:
    content: |
      {% for node in master_eligible_nodes %}
      {{ node['hostname'] + '.' + cluster_vars.dns_user_domain if (cluster_vars.inventory_ip=='private' and cluster_vars.dns_server is defined and cluster_vars.dns_server != "") else hostvars[node['hostname']]['ansible_default_ipv4']['address'] }}
      {% endfor %}
    dest: "{{osearch_conf_dir}}/unicast_hosts.txt"
    owner: "{{osearch_user}}"
    group: "{{osearch_group}}"
    mode: 0600
    force: yes

- name: opensearch/install-config | Create sysctl.d/opensearch.conf
  become: yes
  copy:
    content: |
      vm.max_map_count={{ osearch_max_map_count }}
    dest: "/usr/lib/sysctl.d/opensearch.conf"
    owner: "{{osearch_user}}"
    group: "{{osearch_group}}"
    mode: 0644
    force: yes
  notify: restart opensearch

#This needs to be set programmatically, or opensearch will not start.  A reboot will do it, but not ideal.
- name: opensearch/install-config | set vm.max_map_count
  become: yes
  sysctl:
    name: vm.max_map_count
    value: "{{osearch_max_map_count}}"
    sysctl_set: yes
    state: present
    reload: yes
