---

- include_tasks:
    file: osearch-host-config.yml

- include_tasks:
    file: osearch-binary.yml

- include_tasks:
    file: osearch-plugins.yml

- include_tasks:
    file: osearch-static-config.yml

- include_tasks:
    file: osearch-certs.yml


- name: opensearch/main | flush the handlers
  meta: flush_handlers

- name: opensearch/main | Ensure opensearch is running (e.g. in case an initial run didn't complete or something.  Shouldn't be necessary for 99% of the time.)
  become: yes
  block:
    - name: opensearch/main | Ensure opensearch is running | start & enable opensearch service
      service:
        name: opensearch
        state: started
        enabled: yes
    - name: opensearch/main | Ensure opensearch is running | wait for port 9200 to be open
      wait_for:
        host: localhost
        port: 9200
        timeout: 300

- include_tasks:
    file: osearch-security-accesscontrol.yml

- include_tasks:
    file: osearch-security-config.yml


- name: opensearch/main | Apply index templates
  become: yes
  become_user: "{{osearch_user}}"
  uri:
    url: "https://localhost:9200/_index_template/{{item['name']}}"
    method: PUT
    status_code: 200
    user: "admin"
    password: "{{osearch_static_users['admin']['_password']}}"
    force_basic_auth: yes
    body_format: json
    body: "{{ item['content'] }}"
    client_cert: "{{osearch_ssl_crt_path if osearch_ssl_clientauth_mode in ['REQUIRE', 'OPTIONAL'] else omit}}"
    client_key: "{{osearch_ssl_key_path if osearch_ssl_clientauth_mode in ['REQUIRE', 'OPTIONAL'] else omit}}"
    validate_certs: no
  with_items: "{{ osearch_index_templates }}"
  run_once: yes
  when: osearch_index_templates is defined
