---

- include_tasks:
    file: hostconfig.yml

- include_tasks:
    file: install-binary.yml

- include_tasks:
    file: install-plugins.yml

- include_tasks:
    file: install-config.yml

- include_tasks:
    file: certs.yml


- name: flush the handlers, (re)starting opensearch, if necessary
  meta: flush_handlers


- include_tasks:
    file: users.yml


- name: Apply opensearch templates
  become: yes
  become_user: "{{osearch_user}}"
  uri:
    url: "https://localhost:9200/_index_template/{{item['name']}}"
    method: PUT
    status_code: 200
    user: "admin"
    password: "{{osearch_internal_users['admin']['_password']}}"
    force_basic_auth: yes
    body_format: json
    body: "{{ item['content'] }}"
    client_cert: "{{osearch_ssl_crt_path if osearch_ssl_clientauth_mode in ['REQUIRE', 'OPTIONAL'] else omit}}"
    client_key: "{{osearch_ssl_key_path if osearch_ssl_clientauth_mode in ['REQUIRE', 'OPTIONAL'] else omit}}"
    validate_certs: no
  with_items: "{{ osearch_index_templates }}"
  run_once: yes
  when: osearch_index_templates is defined
