---

#List currently installed plugins
#- name: opensearch/osearch-plugins | Check installed opensearch plugins
#  become: true
#  become_user: "{{osearch_user}}"
#  shell: "{{osearch_home}}/bin/opensearch-plugin list"
#  register: installed_plugins
#  failed_when: "'ERROR' in installed_plugins.stdout"
#  changed_when: False
#  ignore_errors: true
#  environment:
#    CONF_DIR: "{{ osearch_conf_dir }}"
#
#- name: opensearch/osearch-plugins | installed_plugins
#  debug: msg="{{installed_plugins}}"


- name: opensearch/osearch-plugins | Remove custom opensearch plugins (so they are reinstalled below)
  become: true
  become_user: "{{osearch_user}}"
  command: "{{osearch_home}}/bin/opensearch-plugin remove {{ item.name }}"
  with_items: "{{ osearch_plugins | default([]) }}"
  when: not osearch_plugins is none
  register: plugin_uninstalled
  changed_when: plugin_uninstalled.rc == 0
  failed_when: "plugin_uninstalled.rc != 0  and  'not found' not in plugin_uninstalled.stderr"
  notify: restart opensearch
  environment:
    CONF_DIR: "{{ osearch_conf_dir }}"

#- name: opensearch/osearch-plugins | plugin_uninstalled
#  debug: msg="{{plugin_uninstalled}}"


- name: opensearch/osearch-plugins | Install custom opensearch plugins
  become: true
  become_user: "{{osearch_user}}"
  command: "{{osearch_home}}/bin/opensearch-plugin install {{ item.url }} --batch"
  with_items: "{{ osearch_plugins | default([]) }}"
  when: not osearch_plugins is none
  register: plugin_installed
  notify: restart opensearch
  environment:
    CONF_DIR: "{{ osearch_conf_dir }}"

#- name: opensearch/osearch-plugins | plugin_installed
#  debug: msg="{{plugin_installed}}"


#Set permissions on plugins directory
- name: opensearch/osearch-plugins | Set plugin directory permissions
  become: true
  file: state=directory path={{ osearch_home }}/plugins owner={{ osearch_user }} group={{ osearch_group }} recurse=yes
