ca:
   root:
      dn: CN=root.ca.{{ cluster_vars.dns_user_domain }},OU=CA,DC={{ cluster_vars.dns_user_domain }}
      keysize: 2048
      validityDays: 730
      pkPassword: none
      file: root-ca.pem

### Default values and global settings
defaults:
      validityDays: 730
      pkPassword: none
      # Set this to true in order to generate config and certificates for
      # the HTTP interface of nodes
      httpsEnabled: true
      reuseTransportCertificatesForHttp: true
      verifyHostnames: false
      resolveHostnames: false

#
# Specify the nodes of your ES cluster here
#
nodes:
{% for item in groups['data'] %}
  - name: {{ item }}
    dn: CN={{ item }}.{{ cluster_vars.dns_user_domain }},DC={{ cluster_vars.dns_user_domain }}
    dns: {{ item }}.{{ cluster_vars.dns_user_domain }}
    ip: {{ hostvars[item]['ansible_host'] }}
{% endfor %}

#
# Specify the clients that shall access your ES cluster with certificate authentication here
#
# At least one client must be an admin user (i.e., a super-user). Admin users can
# be specified with the attribute admin: true
#
clients:
  - name: admin
    dn: CN=admin,DC={{ cluster_vars.dns_user_domain }}
    admin: true
